# Generated by Django 4.2.3 on 2023-07-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=30)),
                ('ilosc_w_opakowaniu', models.IntegerField(default=0, help_text='imość w pełnym opakowaniu.')),
            ],
        ),
        migrations.CreateModel(
            name='zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_detalu', models.CharField(max_length=30)),
                ('ilosc_opakowan', models.IntegerField()),
            ],
        ),
    ]
