# Generated by Django 4.2.3 on 2023-07-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienia',
            name='osoba_zamawiajaca',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
