# Generated by Django 4.2.3 on 2023-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0002_zamowienia_osoba_zamawiajaca'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienia',
            name='termin_zamowienia',
            field=models.DateTimeField(default='2000-00-00 12:00:00', verbose_name='data'),
            preserve_default=False,
        ),
    ]
