# Generated by Django 4.2.3 on 2023-07-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0004_alter_zamowienia_termin_zamowienia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienia',
            name='termin_zamowienia',
            field=models.DateField(default='0-0-0', verbose_name='data'),
        ),
    ]
